-- ============================================================
-- BURMESE LEARNING DATABASE SCHEMA
-- Supabase PostgreSQL
-- ============================================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. CONSONANTS TABLE
-- Base consonants (က, ခ, ဂ, etc.)
-- ============================================================
DROP TABLE IF EXISTS burmese_consonants CASCADE;
CREATE TABLE burmese_consonants (
    id SERIAL PRIMARY KEY,
    burmese_char VARCHAR(10) NOT NULL UNIQUE,
    devanagari VARCHAR(20),
    romanization VARCHAR(30),
    ipa VARCHAR(30),
    consonant_group VARCHAR(50), -- 'velar', 'palatal', 'retroflex', 'dental', 'labial', etc.
    display_order INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert base consonants
INSERT INTO burmese_consonants (burmese_char, devanagari, romanization, consonant_group, display_order) VALUES
-- Velar (ka group)
('က', 'क', 'ka', 'velar', 1),
('ခ', 'ख', 'kha', 'velar', 2),
('ဂ', 'ग', 'ga', 'velar', 3),
('ဃ', 'घ', 'gha', 'velar', 4),
('င', 'ङ', 'nga', 'velar', 5),
('ငြ', 'ङ', 'ngra', 'velar', 5.1),

-- S-Group (Palatal/Sibilant shifts)
('ကျ', 'च', 'kya', 'palatal', 6),
('ကြ', 'च', 'kra', 'palatal', 6.1),
('ချ', 'छ', 'khya', 'palatal', 7),
('ခြ', 'छ', 'khra', 'palatal', 7.1),
('ဇ', 'ज', 'ja', 'palatal', 8),
('ဂျ', 'ज', 'gya', 'palatal', 8.1),
('ဈ', 'झ', 'jha', 'palatal', 9),
('ဂြ', 'झ', 'gra', 'palatal', 9.1),
('ဉ ', 'ञ', 'nya', 'palatal', 10),
('ည', 'ञ', 'nyya', 'palatal', 10.1),

-- Retroflex (ta group)
('ဋ', 'ट', 'ṭa', 'retroflex', 11),
('ဌ', 'ठ', 'ṭha', 'retroflex', 12),
('ဍ', 'ड', 'ḍa', 'retroflex', 13),
('ဎ', 'ढ', 'ḍha', 'retroflex', 14),
('ဏ', 'ण', 'ṇa', 'retroflex', 15),

-- Dental (ta group)
('တ', 'त', 'ta', 'dental', 16),
('ထ', 'थ', 'tha', 'dental', 17),
('သ', 'थ', 'sa', 'dental', 17.1), -- Mapped to 'थ' per your updated list
('ဒ', 'द', 'da', 'dental', 18),
('ဓ', 'ध', 'dha', 'dental', 19),
('န', 'न', 'na', 'dental', 20),

-- Labial (pa group)
('ပ', 'प', 'pa', 'labial', 21),
('ဖ', 'फ', 'pha', 'labial', 22),
('ဗ', 'ब', 'ba', 'labial', 23),
('ဘ', 'भ', 'bha', 'labial', 24),
('မ', 'म', 'ma', 'labial', 25),

-- Semi-vowels and others
('ယ', 'य', 'ya', 'semivowel', 26),
('ရ', 'र', 'ra', 'semivowel', 27),
('လ', 'ल', 'la', 'semivowel', 28),
('ဝ', 'व', 'wa', 'semivowel', 29),
('ရှ', 'श', 'sha', 'sibilant', 30),
('စ', 'स', 'ca', 'sibilant', 30.1), -- Mapped to 'स' per your updated list
('ဆ', 'स', 'cha', 'sibilant', 30.2), -- Mapped to 'स' per your updated list
('ဿ', 'स्स', 'ssa', 'sibilant', 30.3),
('ဟ', 'ह', 'ha', 'glottal', 31),
('ဠ', 'ळ', 'ḷa', 'lateral', 32),
('အ', 'अ', 'a', 'glottal', 33);

CREATE INDEX idx_consonants_char ON burmese_consonants(burmese_char);
CREATE INDEX idx_consonants_group ON burmese_consonants(consonant_group);


-- ============================================================
-- 2. CATEGORIES TABLE
-- Word categories (Colours, Animals, WHAT, WHY, etc.)
-- ============================================================
DROP TABLE IF EXISTS burmese_categories CASCADE;
CREATE TABLE burmese_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    source VARCHAR(50), -- 'kg_book', 'words', 'recipes'
    parent_category VARCHAR(100), -- For hierarchical grouping
    display_order INT,
    word_count INT DEFAULT 0, -- Denormalized for quick access
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_categories_source ON burmese_categories(source);
CREATE INDEX idx_categories_name ON burmese_categories(name);


-- ============================================================
-- 3. ANCHOR WORDS TABLE
-- Small word units that act as building blocks (like Kanji radicals)
-- Examples: သီး (fruit), ကြော် (fried), ရောင် (color)
-- ============================================================
DROP TABLE IF EXISTS burmese_anchor_words CASCADE;
CREATE TABLE burmese_anchor_words (
    id SERIAL PRIMARY KEY,
    burmese_word VARCHAR(50) NOT NULL,
    devanagari VARCHAR(100),
    romanization VARCHAR(100),
    meaning VARCHAR(200),
    consonant_id INT REFERENCES burmese_consonants(id),
    word_count INT DEFAULT 0, -- How many words use this anchor
    frequency_rank INT, -- Popularity ranking
    is_auto_generated BOOLEAN DEFAULT TRUE, -- TRUE if generated by pattern matching
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(burmese_word)
);

CREATE INDEX idx_anchor_burmese ON burmese_anchor_words(burmese_word);
CREATE INDEX idx_anchor_consonant ON burmese_anchor_words(consonant_id);
CREATE INDEX idx_anchor_frequency ON burmese_anchor_words(frequency_rank);


-- ============================================================
-- 4. MAIN WORDS TABLE
-- All vocabulary words
-- ============================================================
DROP TABLE IF EXISTS burmese_words CASCADE;
CREATE TABLE burmese_words (
    id SERIAL PRIMARY KEY,
    burmese_word VARCHAR(300) NOT NULL,
    devanagari VARCHAR(300),
    romanization VARCHAR(300),
    english_meaning TEXT,
    category_id INT REFERENCES burmese_categories(id),
    source VARCHAR(50), -- 'kg_book', 'words', 'recipes'
    source_sr_no INT, -- Original serial number from source
    difficulty_level INT DEFAULT 1, -- 1=easy, 2=medium, 3=hard
    word_length INT, -- Character count
    syllable_count INT,
    first_consonant_id INT REFERENCES burmese_consonants(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_words_burmese ON burmese_words(burmese_word);
CREATE INDEX idx_words_category ON burmese_words(category_id);
CREATE INDEX idx_words_source ON burmese_words(source);
CREATE INDEX idx_words_consonant ON burmese_words(first_consonant_id);
CREATE INDEX idx_words_difficulty ON burmese_words(difficulty_level);


-- ============================================================
-- 5. WORD-ANCHOR RELATIONSHIP TABLE
-- Links words to their anchor words (many-to-many)
-- A word can contain multiple anchors
-- ============================================================
DROP TABLE IF EXISTS burmese_word_anchors CASCADE;
CREATE TABLE burmese_word_anchors (
    id SERIAL PRIMARY KEY,
    word_id INT REFERENCES burmese_words(id) ON DELETE CASCADE,
    anchor_id INT REFERENCES burmese_anchor_words(id) ON DELETE CASCADE,
    position_in_word INT, -- Where the anchor appears (0 = start)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(word_id, anchor_id)
);

CREATE INDEX idx_word_anchors_word ON burmese_word_anchors(word_id);
CREATE INDEX idx_word_anchors_anchor ON burmese_word_anchors(anchor_id);


-- ============================================================
-- 6. USER PROGRESS TABLE
-- Track learning progress per user
-- ============================================================
DROP TABLE IF EXISTS burmese_user_progress CASCADE;
CREATE TABLE burmese_user_progress (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL, -- Can be localStorage ID or Supabase Auth user ID
    item_type VARCHAR(20) NOT NULL, -- 'consonant', 'anchor', 'word'
    item_id INT NOT NULL, -- References the respective table
    correct_count INT DEFAULT 0,
    incorrect_count INT DEFAULT 0,
    streak INT DEFAULT 0,
    last_practiced TIMESTAMP WITH TIME ZONE,
    attempt_history JSONB DEFAULT '[]', -- Array of {timestamp, correct: boolean}
    mastery_level INT DEFAULT 0, -- 0-5 scale
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, item_type, item_id)
);

CREATE INDEX idx_progress_user ON burmese_user_progress(user_id);
CREATE INDEX idx_progress_type ON burmese_user_progress(item_type);
CREATE INDEX idx_progress_mastery ON burmese_user_progress(mastery_level);


-- ============================================================
-- 7. VIEWS FOR EASY QUERYING
-- ============================================================

-- View: Words grouped by consonant with anchor information
CREATE OR REPLACE VIEW burmese_words_by_consonant AS
SELECT 
    c.id as consonant_id,
    c.burmese_char as consonant,
    c.devanagari as consonant_devanagari,
    c.consonant_group,
    w.id as word_id,
    w.burmese_word,
    w.devanagari as word_devanagari,
    w.english_meaning,
    w.source,
    cat.name as category_name
FROM burmese_consonants c
LEFT JOIN burmese_words w ON w.first_consonant_id = c.id
LEFT JOIN burmese_categories cat ON w.category_id = cat.id
ORDER BY c.display_order, w.burmese_word;


-- View: Anchor words with their child words
CREATE OR REPLACE VIEW burmese_anchor_hierarchy AS
SELECT 
    c.burmese_char as consonant,
    c.devanagari as consonant_devanagari,
    a.id as anchor_id,
    a.burmese_word as anchor_word,
    a.devanagari as anchor_devanagari,
    a.meaning as anchor_meaning,
    a.word_count as anchor_word_count,
    w.id as word_id,
    w.burmese_word,
    w.devanagari as word_devanagari,
    w.english_meaning,
    wa.position_in_word
FROM burmese_consonants c
JOIN burmese_anchor_words a ON a.consonant_id = c.id
LEFT JOIN burmese_word_anchors wa ON wa.anchor_id = a.id
LEFT JOIN burmese_words w ON wa.word_id = w.id
ORDER BY c.display_order, a.frequency_rank, w.burmese_word;


-- View: User mastery summary
CREATE OR REPLACE VIEW burmese_user_mastery AS
SELECT 
    user_id,
    item_type,
    COUNT(*) as total_items,
    SUM(CASE WHEN mastery_level >= 4 THEN 1 ELSE 0 END) as mastered,
    SUM(CASE WHEN mastery_level BETWEEN 2 AND 3 THEN 1 ELSE 0 END) as learning,
    SUM(CASE WHEN mastery_level <= 1 THEN 1 ELSE 0 END) as new_items,
    AVG(correct_count::float / NULLIF(correct_count + incorrect_count, 0)) * 100 as avg_accuracy
FROM burmese_user_progress
GROUP BY user_id, item_type;


-- ============================================================
-- 8. FUNCTIONS FOR ANCHOR WORD EXTRACTION
-- ============================================================

-- Function to get first consonant of a Burmese word
CREATE OR REPLACE FUNCTION get_first_consonant(word TEXT)
RETURNS VARCHAR(10) AS $$
DECLARE
    consonants TEXT[] :=ARRAY['က', 'ခ', 'ဂ', 'ဃ', 'င', 'ငြ', 
                              'ကျ', 'ကြ', 'ချ', 'ခြ', 'စ', 'ဆ', 'ဇ', 'ဂျ', 'ဈ', 'ဂြ', 'ည', 
                              'ဋ', 'ဌ', 'ဍ', 'ဎ', 'ဏ', 'တ', 'ထ', 'ဒ', 'ဓ', 'န',
                              'ပ', 'ဖ', 'ဗ', 'ဘ', 'မ', 'ယ', 'ရ', 'လ', 'ဝ', 'သ', 'ရှ', 'ဿ',
                              'ဟ', 'ဠ', 'အ'];
    i INT;
    char_at TEXT;
BEGIN
    IF word IS NULL OR word = '' THEN
        RETURN NULL;
    END IF;
    
    FOR i IN 1..length(word) LOOP
        char_at := substring(word, i, 1);
        IF char_at = ANY(consonants) THEN
            RETURN char_at;
        END IF;
    END LOOP;
    
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- Function to find anchor words in a given word
CREATE OR REPLACE FUNCTION find_anchors_in_word(word_text TEXT)
RETURNS TABLE(anchor_id INT, anchor_word TEXT, position INT) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a.id,
        a.burmese_word,
        position(a.burmese_word IN word_text)::INT - 1 as pos
    FROM burmese_anchor_words a
    WHERE word_text LIKE '%' || a.burmese_word || '%'
    AND length(a.burmese_word) >= 2
    ORDER BY length(a.burmese_word) DESC, pos;
END;
$$ LANGUAGE plpgsql;


-- Function to auto-generate anchor words from existing words
CREATE OR REPLACE FUNCTION generate_anchor_words(min_frequency INT DEFAULT 3)
RETURNS INT AS $$
DECLARE
    inserted_count INT := 0;
    rec RECORD;
BEGIN
    -- Find common substrings that appear in multiple words
    FOR rec IN (
        WITH substrings AS (
            SELECT 
                substring(burmese_word, i, len) as substr,
                COUNT(DISTINCT id) as word_count
            FROM burmese_words,
                 generate_series(1, length(burmese_word)) as i,
                 generate_series(2, 5) as len
            WHERE i + len - 1 <= length(burmese_word)
            GROUP BY substring(burmese_word, i, len)
            HAVING COUNT(DISTINCT id) >= min_frequency
        )
        SELECT substr, word_count
        FROM substrings
        WHERE get_first_consonant(substr) IS NOT NULL
        ORDER BY word_count DESC
    ) LOOP
        INSERT INTO burmese_anchor_words (burmese_word, word_count, is_auto_generated)
        VALUES (rec.substr, rec.word_count, TRUE)
        ON CONFLICT (burmese_word) DO UPDATE SET word_count = rec.word_count;
        inserted_count := inserted_count + 1;
    END LOOP;
    
    -- Update consonant references
    UPDATE burmese_anchor_words a
    SET consonant_id = c.id
    FROM burmese_consonants c
    WHERE get_first_consonant(a.burmese_word) = c.burmese_char
    AND a.consonant_id IS NULL;
    
    -- Update frequency ranks
    WITH ranked AS (
        SELECT id, ROW_NUMBER() OVER (ORDER BY word_count DESC) as rank
        FROM burmese_anchor_words
    )
    UPDATE burmese_anchor_words a
    SET frequency_rank = r.rank
    FROM ranked r
    WHERE a.id = r.id;
    
    RETURN inserted_count;
END;
$$ LANGUAGE plpgsql;


-- Function to link words to anchors
CREATE OR REPLACE FUNCTION link_words_to_anchors()
RETURNS INT AS $$
DECLARE
    linked_count INT := 0;
    word_rec RECORD;
    anchor_rec RECORD;
BEGIN
    FOR word_rec IN SELECT id, burmese_word FROM burmese_words LOOP
        FOR anchor_rec IN SELECT * FROM find_anchors_in_word(word_rec.burmese_word) LOOP
            INSERT INTO burmese_word_anchors (word_id, anchor_id, position_in_word)
            VALUES (word_rec.id, anchor_rec.anchor_id, anchor_rec.position)
            ON CONFLICT (word_id, anchor_id) DO NOTHING;
            linked_count := linked_count + 1;
        END LOOP;
    END LOOP;
    
    RETURN linked_count;
END;
$$ LANGUAGE plpgsql;


-- Function to update first_consonant_id for all words
CREATE OR REPLACE FUNCTION update_word_consonants()
RETURNS INT AS $$
DECLARE
    updated_count INT := 0;
BEGIN
    UPDATE burmese_words w
    SET first_consonant_id = c.id
    FROM burmese_consonants c
    WHERE get_first_consonant(w.burmese_word) = c.burmese_char
    AND w.first_consonant_id IS NULL;
    
    GET DIAGNOSTICS updated_count = ROW_COUNT;
    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 9. TRIGGER TO AUTO-UPDATE TIMESTAMPS
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_progress_updated
    BEFORE UPDATE ON burmese_user_progress
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();


-- ============================================================
-- 10. ROW LEVEL SECURITY (RLS) FOR USER DATA
-- ============================================================

-- Enable RLS on user progress table
ALTER TABLE burmese_user_progress ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own progress
CREATE POLICY user_progress_select ON burmese_user_progress
    FOR SELECT USING (true); -- Adjust to (auth.uid()::text = user_id) for authenticated users

-- Policy: Users can only insert their own progress
CREATE POLICY user_progress_insert ON burmese_user_progress
    FOR INSERT WITH CHECK (true); -- Adjust for auth

-- Policy: Users can only update their own progress
CREATE POLICY user_progress_update ON burmese_user_progress
    FOR UPDATE USING (true); -- Adjust for auth


-- ============================================================
-- USAGE INSTRUCTIONS
-- ============================================================
/*

STEP 1: Run this entire SQL file in Supabase SQL Editor

STEP 2: Import your word data using the Python script (burmese_data_import.py)
        This will populate: burmese_categories, burmese_words

STEP 3: Generate anchor words automatically:
        SELECT generate_anchor_words(3);  -- min 3 occurrences
        
STEP 4: Link words to anchors:
        SELECT link_words_to_anchors();
        
STEP 5: Update consonant references:
        SELECT update_word_consonants();

QUERYING:

-- Get all words for a consonant (like your grid view):
SELECT * FROM burmese_words_by_consonant WHERE consonant = 'က';

-- Get anchor hierarchy (consonant -> anchor -> words):
SELECT * FROM burmese_anchor_hierarchy WHERE consonant = 'သ';

-- Get popular anchor words:
SELECT * FROM burmese_anchor_words ORDER BY word_count DESC LIMIT 20;

-- Get words containing a specific anchor:
SELECT w.* 
FROM burmese_words w
JOIN burmese_word_anchors wa ON w.id = wa.word_id
JOIN burmese_anchor_words a ON wa.anchor_id = a.id
WHERE a.burmese_word = 'သီး';
*/
